// <auto-generated />
using System;
using Back.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Back.Infrastructure.Database
{
    [DbContext(typeof(LogiTrackDbContext))]
    [Migration("20260405004929_AgregadoDistanciaDePaquete")]
    partial class AgregadoDistanciaDePaquete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Back.Domain.Models.Paquete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision");

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<float>("Distancia")
                        .HasColumnType("real");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<float>("Prioridad")
                        .HasColumnType("real");

                    b.Property<string>("RazonCancelacion")
                        .HasColumnType("text");

                    b.Property<Guid?>("RutaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Back.Domain.Models.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinalizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IniciadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazonCancelacion")
                        .HasColumnType("text");

                    b.Property<Guid>("TransportistaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransportistaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("Back.Domain.Models.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Back.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Back.Domain.Models.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapacidadCarga")
                        .HasColumnType("double precision");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Back.Domain.Models.Operador", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.HasDiscriminator().HasValue("Operador");
                });

            modelBuilder.Entity("Back.Domain.Models.Supervisor", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("Back.Domain.Models.Transportista", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Transportista");
                });

            modelBuilder.Entity("Back.Domain.Models.Paquete", b =>
                {
                    b.HasOne("Back.Domain.Models.Ruta", null)
                        .WithMany("Paquetes")
                        .HasForeignKey("RutaId");

                    b.OwnsOne("Back.Domain.Models.Cliente", "Destinatario", b1 =>
                        {
                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Destinatario_Apellido");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Destinatario_Nombre");

                            b1.HasKey("PaqueteId");

                            b1.ToTable("Paquetes");

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");

                            b1.OwnsOne("Back.Domain.Models.Direccion", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("ClientePaqueteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CP")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Calle")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Ciudad")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Referencia")
                                        .HasColumnType("text");

                                    b2.HasKey("ClientePaqueteId");

                                    b2.ToTable("Paquetes");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientePaqueteId");

                                    b2.OwnsOne("Back.Domain.Models.Ubicacion", "Ubicacion", b3 =>
                                        {
                                            b3.Property<Guid>("DireccionClientePaqueteId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Destinatario_Ubicacion_Latitud");

                                            b3.Property<double>("Longitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Destinatario_Ubicacion_Longitud");

                                            b3.HasKey("DireccionClientePaqueteId");

                                            b3.ToTable("Paquetes");

                                            b3.WithOwner()
                                                .HasForeignKey("DireccionClientePaqueteId");
                                        });

                                    b2.Navigation("Ubicacion");
                                });

                            b1.Navigation("Direccion")
                                .IsRequired();
                        });

                    b.OwnsOne("Back.Domain.Models.Cliente", "Remitente", b1 =>
                        {
                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Remitente_Apellido");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Remitente_Nombre");

                            b1.HasKey("PaqueteId");

                            b1.ToTable("Paquetes");

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");

                            b1.OwnsOne("Back.Domain.Models.Direccion", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("ClientePaqueteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CP")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Calle")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Ciudad")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Referencia")
                                        .HasColumnType("text");

                                    b2.HasKey("ClientePaqueteId");

                                    b2.ToTable("Paquetes");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientePaqueteId");

                                    b2.OwnsOne("Back.Domain.Models.Ubicacion", "Ubicacion", b3 =>
                                        {
                                            b3.Property<Guid>("DireccionClientePaqueteId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Remitente_Ubicacion_Latitud");

                                            b3.Property<double>("Longitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Remitente_Ubicacion_Longitud");

                                            b3.HasKey("DireccionClientePaqueteId");

                                            b3.ToTable("Paquetes");

                                            b3.WithOwner()
                                                .HasForeignKey("DireccionClientePaqueteId");
                                        });

                                    b2.Navigation("Ubicacion");
                                });

                            b1.Navigation("Direccion")
                                .IsRequired();
                        });

                    b.Navigation("Destinatario")
                        .IsRequired();

                    b.Navigation("Remitente")
                        .IsRequired();
                });

            modelBuilder.Entity("Back.Domain.Models.Ruta", b =>
                {
                    b.HasOne("Back.Domain.Models.Transportista", "Transportista")
                        .WithMany()
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Domain.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transportista");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Back.Domain.Models.Ruta", b =>
                {
                    b.Navigation("Paquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
